Fix Course Admin Area Filter Dropdown Values
seas-computing/course-planner pull request #302
Opened 2021-02-03 15:46 UTC by natalynyu

This PR updates the area filter dropdown in the Course Admin tab to use `areas` from the `metadata`. The column header was originally "Course Prefix," but Jonathan Seitz agreed that we could change the column header name to "Area."

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality
      to change)

## Checklist:

- [x] I have run `eslint` on the code
- [x] I have added JSDoc for all of my code (where applicable)
- [x] I have added tests to cover my changes.

## Priority:
- [x] Normal 
- [ ] High 

## Related Issues:

Fixes #269

2021-02-05 19:25 UTC, rmainseas requested changes
This is looking great. Just one small thing.

2021-02-05 19:37 UTC, natalynyu commented on src/client/components/layout/__tests__/AppRouter.test.tsx
> +        return findByText(/Area/);
@rmainseas That's a good point. I was unsure of what to test for here to make sure that the CourseAdmin tab was unique to that page. From the other tests, it looks like we were trying to find the unique column name that only existed on that page and not other pages, but I'm not sure there's something unique I can test for for this tab.
![image](https://user-images.githubusercontent.com/29589689/107080720-aafc2d80-67bf-11eb-8a39-784c8d5be824.png)

2021-02-05 19:47 UTC, rmainseas commented on src/client/components/layout/__tests__/AppRouter.test.tsx
> +        return findByText(/Area/);
Hmm. That's a good point. Perhaps `getByTestId` might help you here

2021-02-05 21:04 UTC, natalynyu commented on src/client/components/layout/__tests__/AppRouter.test.tsx
> +        return findByText(/Area/);
Thanks Robert! I added a test id to Course Admin and updated the test to reflect this.

2021-02-09 17:38 UTC, rmainseas approved these changes
This looks great, merge away

2021-02-09 18:43 UTC, merged